### ISSUE TITLE
REST endpoint giving error post extraction of zip to plugin folder

### ISSUE THREAD

**Issue by vardancse** [teamclairvoyant/airflow-rest-api-plugin#23]
Hi Team,

We've extracted the zip file for 1.0.4 version and moved relevant files to plugin folder and restarted the web server but when tried to hit version GET call, it's showing below response, could you please help what could be the issue? Endpoint we're hitting is <base_url>/admin/rest_api/api?api=version
 ```

                        ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: d706f4fa1e9b
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/src/venv/local/lib/python2.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
TypeError: secure_check() takes exactly 0 arguments (1 given)
```

**Comment by rssanders3** [comment]
Can you confirm what version of Airflow you're running?

**Comment by vardancse** [comment]
It's v1.9

**Comment by sudhakar-nallam** [comment]
Dear @vardancse , 
Can you please confirm do you still have the issue? If so, can you please share a few details so that we can try to reproduce the issue. 

1. Do you have any previous versions of the plugin installed?  
2. Have you checked the Plugin logs to make sure the plugin was loaded successfully?
3. Which OS version and Python version are you using?
4. Any other relevant details that can help us to troubleshoot the issue.

**Comment by vardancse** [comment]
> 4\. other relevant details that can help us to troubleshoot the issue.

Will get back to you in sometime.

**Comment by rssanders3** [comment]
Closing since we haven't heard back with any more details. Please provide details and we'll look into this again.
