### ISSUE TITLE
`flask_jwt_extended` module is required for installation

### ISSUE THREAD

**Issue by xEviL** [teamclairvoyant/airflow-rest-api-plugin#54]
README should mention that `flask_jwt_extended` module is required for installation.
Otherwise one gets:
```
[2019-09-18 17:41:40,087] {{plugins_manager.py:149}} ERROR - No module named 'flask_jwt_extended'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/plugins_manager.py", line 143, in <module>
    m = imp.load_source(namespace, filepath)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/plugins/airflow-rest-api-plugin-1.0.8/plugins/rest_api_plugin.py", line 22, in <module>
    from flask_jwt_extended.view_decorators import jwt_required, verify_jwt_in_request
```

**Comment by sudhakar-nallam** [comment]
@xEviL May I know which version of Airflow you are using? By default Airflow 1.10.4 and higher versions will install this module automatically. FYI - The latest plugin release v1.0.8 is supported only in Airflow versions 1.10.4 and above only. We will update the Readme.

**Comment by xEviL** [comment]
We use `1.10.2` currently via the Docker: https://github.com/puckel/docker-airflow
After installing the `flask_jwt_extended` package seems to be running fine. But we don't use all the features of the plugin.

**Comment by sudhakar-nallam** [comment]
@xEviL Thanks for the update
