### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by idanov** [teamclairvoyant/airflow-rest-api-plugin#9]
I have airflow running on Mac OS X with `python3`, but when I try to install the rest-api-plugin and run airflow, I get this error:
```
user@macbook ~/.airflow/dags$ airflow initdb
[2017-05-11 12:15:15,577] {__init__.py:57} INFO - Using executor SequentialExecutor
[2017-05-11 12:15:15,866] {plugins_manager.py:90} ERROR - No module named 'urllib2'
Traceback (most recent call last):
  File "/Users/user/anaconda/envs/live-toolkit/lib/python3.6/site-packages/airflow/plugins_manager.py", line 79, in <module>
    m = imp.load_source(namespace, filepath)
  File "/Users/user/anaconda/envs/live-toolkit/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/user/.airflow/plugins/rest_api_plugin.py", line 16, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
[2017-05-11 12:15:15,866] {plugins_manager.py:91} ERROR - Failed to import plugin /Users/user/.airflow/plugins/rest_api_plugin.py
DB: sqlite:////Users/user/.airflow/airflow.db
[2017-05-11 12:15:15,889] {db.py:287} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Done.
```

I believe that the problem is that the plugin requires `python2`, but I couldn't find any documentation on the environment requirements of the plugins. Is it possible to add the requirements to the README.md and/or eventually suggest a fix for making it run on `python3`?

**Comment by idanov** [comment]
`sed -i -e 's/urllib2/urllib/g' airflow-rest-api-plugin-1.0.1/plugins/rest_api_plugin.py` fixed it for me.

**Comment by rssanders3** [comment]
Yes the current plugin only supports python 2. I will add this requirement to the README.

I recall seeing some people have forked the project and created versions that worked with python 3. I still haven't had a chance to look into making it compatible with python 2 and 3 at the same time. Ill be working on that next. 

OK glad you found a solution.

**Comment by rssanders3** [comment]
Actually with your fix I don't think the _refresh_dag_ API will work. 

Since the following is used to call another service: _urllib2.urlopen(refresh_dag_url)_
By renaming it to urllib the command will become: _urllib.urlopen(refresh_dag_url)_
But in python3 urllib doesn't have the function .urlopen()

**Comment by rssanders3** [comment]
I modified how the _refresh_dag_ operation is working and now it should work in both python2 and python3: https://github.com/teamclairvoyant/airflow-rest-api-plugin/commit/5a13d306580647c99438d515198ddc5c86459948

This change will be apart of 1.0.2 release which I will create soon. There's a few more things I want to add to this release.

**Comment by idanov** [comment]
Great, thank you for fixing it so fast!

**Comment by rssanders3** [comment]
No problem.

Created a release with these changes: https://github.com/teamclairvoyant/airflow-rest-api-plugin/releases/tag/v1.0.2
